### ISSUE TITLE
Fix broken Action: Fetch cabinet statement

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/gov-za-multilingual#20]
Description:  Github action `Fetch cabinet statement` failing 

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cabinent_statements = helper_functions.get_cabinent_statements_urls(date) #read cabinet statements until date
  File "/home/runner/work/gov-za-multilingual/gov-za-multilingual/src/gov_cab_statements_scrape/helper_functions.py", line 60, in get_cabinent_statements_urls
    statement['title'] = row.find('td').find('a').text
AttributeError: 'int' object has no attribute 'find
```

Looks like a simple fix, maybe they changed something in the website structure

**Comment by lastrucci01** [comment]
#21
